WIFI_SSID = "XXXXXXXXXX"
WIFI_PASSWORD = "XXXXXXXXXX"

GEOLOCATION_SECRET = "XXXXXXXXXX"

FACEBOOK_SECRET = "XXXXXXXXXX"

SUBSCRIBERS = {
  "Subscriber 1": "XXXXXXXXXX",
  "Subscriber 2": "XXXXXXXXXX",
}
